imroves

diff --git a/nginx1.16/Dockerfile b/nginx1.16/Dockerfile
--- a/nginx1.16/Dockerfile
+++ b/nginx1.16/Dockerfile
@@ -8,79 +8,168 @@ ENV NGINX_VERSION 1.16.0
 ENV NJS_VERSION   0.3.2
 ENV PKG_RELEASE   1
 
-RUN set -x \
-# create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
-    && apkArch="$(cat /etc/apk/arch)" \
-    && nginxPackages=" \
-        nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
-        nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} \
-        nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} \
-        nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
-        nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${PKG_RELEASE} \
-    " \
-    && case "$apkArch" in \
-        x86_64) \
-# arches officially built by upstream
-            set -x \
-            && KEY_SHA512="e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a *stdin" \
-            && apk add --no-cache --virtual .cert-deps \
-                openssl curl ca-certificates \
-            && curl -o /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
-            && if [ "$(openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout | openssl sha512 -r)" = "$KEY_SHA512" ]; then \
-                echo "key verification succeeded!"; \
-                mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
-            else \
-                echo "key verification failed!"; \
-                exit 1; \
-            fi \
-            && printf "%s%s%s\n" \
-                "http://nginx.org/packages/alpine/v" \
-                `egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release` \
-                "/main" \
-            | tee -a /etc/apk/repositories \
-            && apk del .cert-deps \
-            ;; \
-        *) \
-# we're on an architecture upstream doesn't officially build for
-# let's build binaries from the published packaging sources
-            set -x \
-            && tempDir="$(mktemp -d)" \
-            && chown nobody:nobody $tempDir \
-            && apk add --no-cache --virtual .build-deps \
-                gcc \
-                libc-dev \
-                make \
-                openssl-dev \
-                pcre-dev \
-                zlib-dev \
-                linux-headers \
-                libxslt-dev \
-                gd-dev \
-                geoip-dev \
-                perl-dev \
-                libedit-dev \
-                mercurial \
-                bash \
-                alpine-sdk \
-                findutils \
-            && su nobody -s /bin/sh -c " \
-                export HOME=${tempDir} \
-                && cd ${tempDir} \
-                && hg clone https://hg.nginx.org/pkg-oss \
-                && cd pkg-oss \
-                && hg up -r 417 \
-                && cd alpine \
-                && make all \
-                && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
-                && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
-                " \
-            && echo "${tempDir}/packages/alpine/" >> /etc/apk/repositories \
-            && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
-            && apk del .build-deps \
-            ;; \
-    esac \
+#ENV NGINX_VERSION 1.16.0
+ENV LUA_MODULE_VERSION 0.10.13
+ENV DEVEL_KIT_MODULE_VERSION 0.3.0
+ENV LUAJIT_LIB=/usr/lib
+ENV LUAJIT_INC=/usr/include/luajit-2.1
+
+RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
+	wget \
+	git \
+	rsync  \
+	curl \
+	tar \
+	xz \
+	ca-certificates \
+	libressl \
+	supervisor \
+	logrotate \
+	pcre \
+        && mkdir -p /var/log/supervisor \
+        && addgroup -g 1000 -S www-data \
+        && adduser -u 1000 -D -S -G www-data www-data \
+        && addgroup -S nginx \
+        && adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx 
+
+
+RUN apk add --no-cache --virtual .build-deps \
+    gnupg \
+    musl-dev \
+    autoconf \
+    gcc \
+    g++ \
+    make \
+    libc-dev \
+    libressl-dev \
+    pcre-dev \
+    zlib-dev \
+    linux-headers \
+    libxslt-dev \
+    gd-dev \
+    geoip-dev \
+    perl-dev \
+    luajit-dev \
+    coreutils \
+    curl-dev \
+    libedit-dev \
+    libxml2-dev \
+    sqlite-dev \
+    dpkg \
+    dpkg-dev \
+    libevent-dev \
+    libmemcached-dev \
+    file \
+    libc-dev \
+    pkgconf \
+    re2c \
+    freetype-dev \
+    libjpeg-turbo-dev \
+    libpng-dev \
+        libmcrypt-dev 
+
+    RUN GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
+  && CONFIG="\
+    --prefix=/etc/nginx \
+    --sbin-path=/usr/sbin/nginx \
+    --modules-path=/usr/lib/nginx/modules \
+    --conf-path=/etc/nginx/nginx.conf \
+    --error-log-path=/log/nginx.error.log \
+    --http-log-path=/log/nginx.access.log \
+    --pid-path=/var/run/nginx.pid \
+    --lock-path=/var/run/nginx.lock \
+    --http-client-body-temp-path=/var/cache/nginx/client_temp \
+    --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
+    --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
+    --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
+    --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
+    --user=nginx \
+    --group=nginx \
+    --with-http_ssl_module \
+    --with-http_realip_module \
+    --with-http_addition_module \
+    --with-http_sub_module \
+    --with-http_dav_module \
+    --with-http_flv_module \
+    --with-http_mp4_module \
+    --with-http_gunzip_module \
+    --with-http_gzip_static_module \
+    --with-http_random_index_module \
+    --with-http_secure_link_module \
+    --with-http_stub_status_module \
+    --with-http_auth_request_module \
+    --with-http_xslt_module=dynamic \
+    --with-http_image_filter_module=dynamic \
+    --with-http_geoip_module=dynamic \
+    --with-http_perl_module=dynamic \
+    --with-threads \
+    --with-stream \
+    --with-stream_ssl_module \
+    --with-stream_ssl_preread_module \
+    --with-stream_realip_module \
+    --with-stream_geoip_module=dynamic \
+    --with-http_slice_module \
+    --with-mail \
+    --with-mail_ssl_module \
+    --with-compat \
+    --with-file-aio \
+    --with-http_v2_module \
+#    --add-module=/usr/src/ngx_devel_kit-$DEVEL_KIT_MODULE_VERSION \
+#    --add-module=/usr/src/lua-nginx-module-$LUA_MODULE_VERSION \
+  " \
+  && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
+  && curl -fSL http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
+  && curl -fSL https://github.com/simpl/ngx_devel_kit/archive/v$DEVEL_KIT_MODULE_VERSION.tar.gz -o ndk.tar.gz \
+  && curl -fSL https://github.com/openresty/lua-nginx-module/archive/v$LUA_MODULE_VERSION.tar.gz -o lua.tar.gz \
+  && export GNUPGHOME="$(mktemp -d)" \
+  && found=''; \
+  for server in \
+    ha.pool.sks-keyservers.net \
+    hkp://keyserver.ubuntu.com:80 \
+    hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu \
+  ; do \
+    echo "Fetching GPG key $GPG_KEYS from $server"; \
+    gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+  done; \
+  test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+  gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
+  #&& rm -r "$GNUPGHOME" nginx.tar.gz.asc \
+  && mkdir -p /usr/src \
+  && tar -zxC /usr/src -f nginx.tar.gz \
+  && tar -zxC /usr/src -f ndk.tar.gz \
+  && tar -zxC /usr/src -f lua.tar.gz \
+  && rm nginx.tar.gz ndk.tar.gz lua.tar.gz \ 
+  && cd /usr/src/nginx-$NGINX_VERSION \
+  && ./configure $CONFIG --with-debug \
+  && make -j$(getconf _NPROCESSORS_ONLN) \
+  && mv objs/nginx objs/nginx-debug \
+  && mv objs/ngx_http_xslt_filter_module.so objs/ngx_http_xslt_filter_module-debug.so \
+  && mv objs/ngx_http_image_filter_module.so objs/ngx_http_image_filter_module-debug.so \
+  && mv objs/ngx_http_geoip_module.so objs/ngx_http_geoip_module-debug.so \
+  && mv objs/ngx_http_perl_module.so objs/ngx_http_perl_module-debug.so \
+  && mv objs/ngx_stream_geoip_module.so objs/ngx_stream_geoip_module-debug.so \
+  && ./configure $CONFIG \
+  && make -j$(getconf _NPROCESSORS_ONLN) \
+  && make install \
+  && rm -rf /etc/nginx/html/ \
+  && mkdir /etc/nginx/conf.d/ \
+  && mkdir -p /usr/share/nginx/html/ \
+  && install -m644 html/index.html /usr/share/nginx/html/ \
+  && install -m644 html/50x.html /usr/share/nginx/html/ \
+  && install -m755 objs/nginx-debug /usr/sbin/nginx-debug \
+  && install -m755 objs/ngx_http_xslt_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_xslt_filter_module-debug.so \
+  && install -m755 objs/ngx_http_image_filter_module-debug.so /usr/lib/nginx/modules/ngx_http_image_filter_module-debug.so \
+  && install -m755 objs/ngx_http_geoip_module-debug.so /usr/lib/nginx/modules/ngx_http_geoip_module-debug.so \
+  && install -m755 objs/ngx_http_perl_module-debug.so /usr/lib/nginx/modules/ngx_http_perl_module-debug.so \
+  && install -m755 objs/ngx_stream_geoip_module-debug.so /usr/lib/nginx/modules/ngx_stream_geoip_module-debug.so \
+  && ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
+  && strip /usr/sbin/nginx* \
+  && strip /usr/lib/nginx/modules/*.so \
+  && rm -rf /usr/src/nginx-$NGINX_VERSION 
+
+
+RUN apk del .build-deps \
     && apk add --no-cache $nginxPackages \
 # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
@@ -108,9 +197,10 @@ RUN set -x \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
     && apk add --no-cache tzdata \
+	&& mkdir /app-log \
 # forward request and error logs to docker log collector
-    && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log
+    && ln -sf /dev/stdout /app-log/access.log \
+    && ln -sf /dev/stderr /app-log/error.log
 
 EXPOSE 80
 
